version: "3.9"
volumes:
  psysh-store:
services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./:/work/code:cached
      - type: volume
        source: psysh-store
        target: /root/.config/psysh
        volume:
          nocopy: true
